#pragma once
#include "SDK.h"

void ReplaceString(std::string& input, const std::string& what, const std::string& with_what)
{
	size_t index;
	index = input.find(what);
	while (index != std::string::npos)
	{
		input.replace(index, what.size(), with_what);
		index = input.find(what, index + with_what.size());
	}
}


namespace chat_bot {

	std::vector<std::string> chat_spam_eng = {

		"MASSAS.PW - REDUCE YOUR RISK OF BEING OWNED!",
		"MASSAS.PW - WAY TO THE TOP!",
		"MASSAS.PW - BEST CSGO CHEAT!",
		"MASSAS.PW - NOW WITH BLACKJACK AND HOOKERS!",
		"MASSAS.PW - BUTTHURT IN 10 SECONDS FLAT!",
		"MASSAS.PW - WHOLE SERVER OBSERVING!",
		"MASSAS.PW - GET BACK TO PWNING!",
		"MASSAS.PW - WHEN PVP IS TOO HARDCORE!",
		"MASSAS.PW - CAN CAUSE KIDS TO RAGE!",
		"MASSAS.PW - F2C NOOBS WILL BE 100% NERFED!",
		"GET GOOD, GET MASSAS.PW!",
		"MASSAS.PW - WAY TO THE TOP",
		"CHECK OUT MASSAS.PW FOR MORE INFORMATION!",
		"PWNING REATRDS SINCE 2016 - MASSAS.PW",
		"STOP GETTING MAD AND STABILIZE YOUR MOOD WITH MASSAS.PW!",
		"SAVE YOUR MONEY AND GET MASSAS.PW! IT IS 10€!",
		"GOT ROLLED BY MASSAS.PW? HEY, THAT MEANS IT'S TIME TO GET MASSAS.PW!!",
	};


	std::vector<std::string> chat_spam_pt = {

		"MASSAS.PW - REDUZ O TEU RISCO DE PERDER!",
		"MASSAS.PW - CAMINHO PARA O TOPO!",
		"MASSAS.PW - O MELHOR CHEAT DE CSGO!",
		"MASSAS.PW - AGORA COM SUECA E PUTAS!",
		"MASSAS.PW - BUTTHURT EM 10 SEGUNDOS!",
		"MASSAS.PW - TODO O SERVER A OBSERVAR!",
		"MASSAS.PW - QUANDO O PVP ESTA MUITO QUENTE!",
		"MASSAS.PW - PODE CAUSAR CHORO EM CRIANÇAS!",
		"MASSAS.PW - NERDS F2C VAO TAR 100% NERFADOS!",
		"COMPRA OURO, COMPRA MASSAS.PW!",
		"VISITA MASSAS.PW PARA MAIS INFORMAÇÃO!",
		"DESTRUINDO RETARDADOS DESDE 2016 - MASSAS.PW",
		"PARA DE CHORAR E ESTABILIZA O TEU HUMOR COM MASSAS.PW!",
		"POUPA O TEU DINEHIRO E COMPRA MASSAS.PW! APENAS 10€!",
		"MORRESTE PARA MASSAS.PW? HEY, ISSO SIGNIFICA QUE ESTA NA HORA DE ADEQUIRIR MASSAS.PW!!",
	};

}